# Generated by Django 4.2.3 on 2023-07-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
